### ISSUE TITLE
The status getter returning `undefined` instead of action `id`

### ISSUE THREAD

**Issue by s1nz** [mrichar1/jsonapi-vuex#75] opened 2019-07-15 10:56 UTC
If you try to use status getter with Axios the `undefined` returned instead of action `id`.

Thanks for your help.

**Comment by mrichar1** [comment] 2019-07-15 11:59
It looks like something is indeed stripping the status `id` off of the promise. I've added some debugging to the code, and the promise is definitely still having the `id` added, but it doesn't appear on the promise returned by calling `this.$store.dispatch`.

A quick test of the basics shows that it does at least work in 'basic' JS:

https://codepen.io/mrichar1/pen/pXXEvK

So it must be Vue-specific. I'll see if I can figure out what's happening and try to get this working again...

**Comment by mrichar1** [comment] 2019-07-16 09:15
For info, this looks like it's an upstream bug, and not something specific to this module:

https://github.com/vuejs/vuex/issues/1581

**Comment by s1nz** [comment] 2019-07-16 09:37
> For info, this looks like it's an upstream bug, and not something specific to this module:
> 
> [vuejs/vuex#1581](https://github.com/vuejs/vuex/issues/1581)

Thanks for the update!

**Comment by mrichar1** [comment] 2019-09-23 09:28
Keeping open as a reminder to track upstream bug.

**Comment by mrichar1** [comment] 2019-11-18 15:27
It appears that the upstream issue has effectively been closed 'WONTFIX' since it's expected that actions may create new Promises, rather than preserving the one generated by the function.

This means that we need to investigate an alternative way of handling status updates - possibly involving passing in callbacks to actions?

**Comment by geoidesic** [comment] 2019-11-24 11:43
Not sure if this will help you but this is how I'm getting around this issue currently:
```
export function status(state, getters) {
  // get the most recent _jv status
  const pinged = getters.get();
  const key = Object.keys(pinged._jv)
    .sort()
    .reverse()[0];
  if (empty(pinged._jv)) return "OFFLINE";
  if (pinged._jv[key].status === "ERROR") {
    return "OFFLINE";
  }
  if (pinged._jv[key].status === "LOADING") {
    return "CHECKING";
  } else {
    return "ONLINE";
  }
}
```

**Comment by mrichar1** [comment] 2019-11-24 14:59
The issue is that `status` is updated from `actions`, which are all asynchronous. This means that unless you know there is only ever one action 'in-flight' this approach is risky.

I believe the correct solution now is probably to pass a 'callback' function or variable to the action as an argument, which will then be called/modified by the action in each of the places it currently updates the status. I need to sit down with the code though so nothing is finalised yet.

**Comment by Stefano1990** [comment] 2020-01-31 08:22
Just to save people some time, should it be communicated in the documentation that this feature is currently not working as intended?

**Comment by mrichar1** [comment] 2020-01-31 08:29
Yes, I had hoped to have worked through an alternative by now, but given I've not had time yet, and the alternative would require the docs to change anyway, I'll update the docs to reflect it's not working.

**Comment by mrichar1** [comment] 2020-02-03 10:09
I have a new way of doing this worked out, and am starting work on this today. However it would sit better on a refactored codebase which I'm working on first, so I've pushed a new release without the broken code in the meantime.

**Comment by mrichar1** [comment] 2020-02-04 18:12
That's the new approach in as a PR. I'll merge this in soon and release (`4.1.0`). For anyone who's interested please red through the 'Action Status' section of `README.md` and see if this new way of tracking status seems suitable for your use cases?

**Closed** 2020-03-07 11:25 UTC
Labels: bug, upstream
